Source commands first from <warden_install>/commands, then <project>/.warden/commands, then home .warden/commands

diff --git a/bin/warden b/bin/warden
--- a/bin/warden
+++ b/bin/warden
@@ -13,6 +13,7 @@ readonly WARDEN_DIR="$(
   && pwd
 )"
 source "${WARDEN_DIR}/utils/core.sh"
+source "${WARDEN_DIR}/utils/env.sh"
 
 ## verify docker-compose is installed
 if ! which docker-compose >/dev/null; then
@@ -34,15 +35,34 @@ export readonly WARDEN_COMPOSER_DIR="${WARDEN_COMPOSER_DIR:-"$HOME/.composer"}"
 ## declare variables for flags and arguments
 declare WARDEN_HELP=
 declare WARDEN_PARAMS=()
-declare WARDEN_COMMAND=
-declare WARDEN_ANYARGS=(svc env db sync shell debug)
+declare WARDEN_CMD_VERB=
+declare WARDEN_CMD_EXEC=
+declare WARDEN_CMD_HELP=
+declare WARDEN_CMD_ANYARGS=(svc env db sync shell debug)
 
 ## parse first argument as command and determine validity
-if (( "$#" )) && [[ -f "${WARDEN_DIR}/commands/${1}.cmd" ]]; then
-  WARDEN_COMMAND="$1"
-  shift
-else
-  WARDEN_COMMAND=usage
+if (( "$#" )); then
+  ## local project directory if running within one; don't fail if it can't be found
+  WARDEN_ENV_PATH="$(locateEnvPath 2>/dev/null)" || true
+
+  if [[ -f "${WARDEN_DIR}/commands/${1}.cmd" ]]; then
+    WARDEN_CMD_VERB="$1"
+    WARDEN_CMD_EXEC="${WARDEN_DIR}/commands/${1}.cmd"
+    WARDEN_CMD_HELP="${WARDEN_DIR}/commands/${1}.help"
+    shift
+  elif [[ -f "${WARDEN_ENV_PATH}/.warden/commands/${1}.cmd" ]]; then
+    WARDEN_CMD_VERB="$1"
+    WARDEN_CMD_EXEC="${WARDEN_ENV_PATH}/.warden/commands/${1}.cmd"
+    WARDEN_CMD_HELP="${WARDEN_ENV_PATH}/.warden/commands/${1}.help"
+    shift
+  elif [[ -f "${WARDEN_HOME_DIR}/commands/${1}.cmd" ]]; then
+    WARDEN_CMD_VERB="$1"
+    WARDEN_CMD_EXEC="${WARDEN_HOME_DIR}/commands/${1}.cmd"
+    WARDEN_CMD_HELP="${WARDEN_HOME_DIR}/commands/${1}.help"
+    shift
+  else
+    WARDEN_HELP=1
+  fi
 fi
 
 ## parse arguments
@@ -54,10 +74,10 @@ while (( "$#" )); do
       ;;
     --) # end argument parsing (unless command is on 'anyargs' list and consumes anything as params)
       shift
-      containsElement "${WARDEN_COMMAND}" "${WARDEN_ANYARGS[@]}" || break
+      containsElement "${WARDEN_CMD_VERB}" "${WARDEN_CMD_ANYARGS[@]}" || break
       ;;
     -*|--*=) # unsupported flags (unless command is on 'anyargs' list and consumes anything as params)
-      containsElement "${WARDEN_COMMAND}" "${WARDEN_ANYARGS[@]}" && break
+      containsElement "${WARDEN_CMD_VERB}" "${WARDEN_CMD_ANYARGS[@]}" && break
       fatal "Unsupported flag $1"
       ;;
     *) # preserve positional arguments
@@ -73,4 +93,4 @@ if [[ ${WARDEN_HELP} ]]; then
 fi
 
 ## execute sub-command in context of this script
-source "${WARDEN_DIR}/commands/${WARDEN_COMMAND}.cmd"
+source "${WARDEN_CMD_EXEC}"
