Update some messaging and relocate docker-compose check to entrypoint rather than 'install' command

diff --git a/bin/warden b/bin/warden
--- a/bin/warden
+++ b/bin/warden
@@ -14,8 +14,17 @@ readonly WARDEN_DIR="$(
 )"
 source "${WARDEN_DIR}/utils/core.sh"
 
-## define environment requirements
-readonly WARDEN_REQUIRED_DOCKER_COMPOSE="1.25.0"
+## verify docker-compose is installed
+if ! which docker-compose >/dev/null; then
+  fatal "docker-compose could not be found; please install and try again."
+fi
+
+## verify docker-compose meets version constraint
+DOCKER_COMPOSE_REQUIRE="1.25.0"
+DOCKER_COMPOSE_VERSION="$(docker-compose -v | grep -oE '[0-9\.]+' | head -n1)"
+if ! test $(version ${DOCKER_COMPOSE_VERSION}) -ge $(version ${DOCKER_COMPOSE_REQUIRE}); then
+  fatal "docker-compose version should be ${DOCKER_COMPOSE_REQUIRE} or higher (${DOCKER_COMPOSE_VERSION} installed)"
+fi
 
 ## define and export global shared directory paths
 export readonly WARDEN_HOME_DIR="${WARDEN_HOME_DIR:-"$HOME/.warden"}"
